/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Listas.ListadeUsuarios;
import Listas.Nodo;
import Listas.NodoUsuario;
import Listas.Simple;
import javax.swing.JOptionPane;

/**
 *
 * @author eliot
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }
    public ListadeUsuarios listaUsuario = new ListadeUsuarios();
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        btn_Biblioteca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_Convertidor = new javax.swing.JButton();
        btn_Editor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usac Viewer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        txt_Usuario.setBackground(new java.awt.Color(153, 204, 255));
        txt_Usuario.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txt_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_Usuario.setBorder(null);
        txt_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 130, 30));

        btn_Biblioteca.setBackground(new java.awt.Color(153, 204, 255));
        btn_Biblioteca.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btn_Biblioteca.setForeground(new java.awt.Color(0, 0, 0));
        btn_Biblioteca.setText("Ingresar a la Biblioteca");
        btn_Biblioteca.setBorder(null);
        btn_Biblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Biblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BibliotecaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Biblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 180, 50));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Menu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 130, 50));

        btn_Convertidor.setBackground(new java.awt.Color(153, 204, 255));
        btn_Convertidor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btn_Convertidor.setForeground(new java.awt.Color(0, 0, 0));
        btn_Convertidor.setText("Ingresar al Convertidor");
        btn_Convertidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Convertidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConvertidorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Convertidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 220, 50));

        btn_Editor.setBackground(new java.awt.Color(153, 204, 255));
        btn_Editor.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btn_Editor.setForeground(new java.awt.Color(0, 0, 0));
        btn_Editor.setText("Ingresar al Editor");
        btn_Editor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Editor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Editor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BibliotecaActionPerformed

         NodoUsuario usuario = new NodoUsuario();
        
          if (!txt_Usuario.getText().isEmpty()) {
            String nombre = txt_Usuario.getText();
              if (!listaUsuario.existeUsuario(nombre)) {
                 listaUsuario.add(nombre);
                 usuario.setNombreUsuario(nombre);
                 
              }else{
                  usuario.setNombreUsuario(listaUsuario.getUsuario(nombre).getNombreUsuario());
              }
                 listaUsuario.mostrar();
                
                 Biblioteca biblioteca = new Biblioteca(this,nombre);
                 biblioteca.setVisible(true);
                 biblioteca.setLocationRelativeTo(null);
                 this.setVisible(false);
             
        }else{
          JOptionPane.showMessageDialog(this,"El campo debe estar lleno");
          }
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BibliotecaActionPerformed

    private void btn_EditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditorActionPerformed

            Editor editor = new Editor ();
            editor.setVisible(true);
            editor.setLocationRelativeTo(null);
            this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EditorActionPerformed

    private void btn_ConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConvertidorActionPerformed

        Convertidor convertidor = new Convertidor();
        convertidor.setVisible(true);
        convertidor.setLocationRelativeTo(null);
        this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ConvertidorActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Biblioteca;
    private javax.swing.JButton btn_Convertidor;
    private javax.swing.JButton btn_Editor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
